In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
df = pd.read_csv('/content/pizza_sales_cleaned2.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pizza_id        48620 non-null  int64
 1   order_id        48620 non-null  int64
 2   quantity        48620 non-null  int64
 3   order_date      48620 non-null  object
 4   order_time      48620 non-null  object
 5   unit_price      48620 non-null  float64
 6   total_price     48620 non-null  float64
 7   pizza_size      48620 non-null  object
 8   pizza_category  48620 non-null  object
 9   pizza_name      48620 non-null  object
 10  month           48620 non-null  int64
 11  month_name      48620 non-null  object
 12  day_of_week     48620 non-null  object
 13  quarter         48620 non-null  int64
 14  hour            48620 non-null  int64
dtypes: float64(2), int64(6), object(7)
memory usage: 5.6+ MB

In [ ]:
df.info()

NameError: name 'df' is not defined

In [4]:
df.describe(include="all")

,pizza_id,order_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_name,month,month_name,day_of_week,quarter,hour
count,48620.000000,48620.000000,48620.000000,48620,48620,48620.000000,48620.000000,48620,48620,48620,48620.000000,48620,48620,48620.000000,48620.000000
unique,NaN,NaN,NaN,358,16382,NaN,NaN,5,4,32,NaN,12,7,NaN,NaN
top,NaN,NaN,NaN,2015-11-26,12:32:00,NaN,NaN,L,Classic,The Classic Deluxe Pizza,NaN,January,Friday,NaN,NaN
freq,NaN,NaN,NaN,261,26,NaN,NaN,18526,14579,2416,NaN,4288,7723,NaN,NaN
mean,24310.500000,10701.479761,1.019622,NaN,NaN,16.494132,16.821474,NaN,NaN,NaN,6.432476,NaN,NaN,2.484554,15.911806
std,14035.529381,6180.119770,0.143077,NaN,NaN,3.621789,4.437398,NaN,NaN,NaN,3.435386,NaN,NaN,1.116890,3.149836
min,1.000000,1.000000,1.000000,NaN,NaN,9.750000,9.750000,NaN,NaN,NaN,1.000000,NaN,NaN,1.000000,9.000000
25%,12155.750000,5337.000000,1.000000,NaN,NaN,12.750000,12.750000,NaN,NaN,NaN,3.000000,NaN,NaN,1.000000,13.000000
50%,24310.500000,10682.500000,1.000000,NaN,NaN,16.500000,16.500000,NaN,NaN,NaN,6.000000,NaN,NaN,2.000000,16.000000
75%,36465.250000,16100.000000,1.000000,NaN,NaN,20.250000,20.500000,NaN,NaN,NaN,9.000000,NaN,NaN,3.000000,18.000000
max,48620.000000,21350.000000,4.000000,NaN,NaN,35.950000,83.000000,NaN,NaN,NaN,12.000000,NaN,NaN,4.000000,23.000000

In [ ]:
df.isnull().sum()

pizza_id             0
order_id             1
pizza_name_id        1
quantity             1
order_date           1
order_time           1
unit_price           1
total_price          1
pizza_size           1
pizza_category       1
pizza_ingredients    1
pizza_name           1
dtype: int64

In [ ]:
print("Shape:", df.shape)
print(df[['pizza_id', 'order_id', 'quantity']].dtypes)

Shape: (24537, 12)
pizza_id      int64
order_id    float64
quantity    float64
dtype: object

In [ ]:
print("pizza_id unique decimals:", (df['pizza_id']% 1 !=0).sum())

pizza_id unique decimals: 0

In [ ]:
print("order_id unique decimals:", (df['order_id']% 1 !=0).sum())
print("quantity unique decimals:", (df['quantity']% 1 !=0).sum())

order_id unique decimals: 1
quantity unique decimals: 1

In [ ]:

df['pizza_id'] = df['pizza_id'].fillna(0)
df['order_id'] = df['order_id'].fillna(0)
df['quantity'] = df['quantity'].fillna(0)


df['pizza_id'] = df['pizza_id'].astype(int)
df['order_id'] = df['order_id'].astype(int)
df['quantity'] = df['quantity'].astype(int)

In [ ]:
print(df[['pizza_id','order_id','quantity']].dtypes)
print(df[['pizza_id','order_id','quantity']].head())

pizza_id      int64
order_id    float64
quantity    float64
dtype: object
   pizza_id  order_id  quantity
0         1       1.0       1.0
1         2       2.0       1.0
2         3       2.0       1.0
3         4       2.0       1.0
4         5       2.0       1.0

In [ ]:
print(df['order_date'].head(10))
print(df['order_date'].dtype)

0    1/1/2015
1    1/1/2015
2    1/1/2015
3    1/1/2015
4    1/1/2015
5    1/1/2015
6    1/1/2015
7    1/1/2015
8    1/1/2015
9    1/1/2015
Name: order_date, dtype: object
object

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed', dayfirst=False)

print(df['order_date'].head(5))
print(df['order_date'].dtype)

0   2015-01-01
1   2015-01-01
2   2015-01-01
3   2015-01-01
4   2015-01-01
Name: order_date, dtype: datetime64[ns]
datetime64[ns]

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed', dayfirst=False)

print(df['order_date'].dtype)

datetime64[ns]

In [ ]:
print(df['pizza_id'].isnull().sum())
print(df['order_id'].isnull().sum())
print(df['quantity'].isnull().sum())

0
0
0

In [ ]:
print(df[df['order_id'].isnull()])

       pizza_id  order_id pizza_name_id  quantity order_date order_time  \
24536     24537       NaN           NaN       NaN        NaN        NaN

       unit_price  total_price pizza_size pizza_category pizza_ingredients  \
24536         NaN          NaN        NaN            NaN               NaN

      pizza_name
24536        NaN

In [ ]:
df = df.dropna(subset=['pizza_id', 'order_id', 'quantity'])
print("Rows after dropping NaN:", len(df))

Rows after dropping NaN: 24536

In [ ]:
df['order_date'] = df['order_date'].dt.strftime('%Y-%m-%d')

print(df['order_date'].head(5))

0    2015-01-01
1    2015-01-01
2    2015-01-01
3    2015-01-01
4    2015-01-01
Name: order_date, dtype: object

In [ ]:
print(df['order_date'].dtype)

object

In [ ]:
print(df['order_date'].dtype)

object

In [ ]:
print(df['order_date'].head(5))
print(df['order_date'].tail(5))

0    2015-01-01
1    2015-01-01
2    2015-01-01
3    2015-01-01
4    2015-01-01
Name: order_date, dtype: object
24531    2015-06-30
24532    2015-06-30
24533    2015-06-30
24534    2015-06-30
24535    2015-06-30
Name: order_date, dtype: object

In [ ]:
print("Earliest date:", df['order_date'].max())
print("Earliest date:", df['order_date'].min())

Earliest date: 2015-12-06
Earliest date: 2015-01-01

In [ ]:
print(df['order_time'].head(5))
print(df['order_time'].dtype)

0    11:38:36
1    11:57:40
2    11:57:40
3    11:57:40
4    11:57:40
Name: order_time, dtype: object
object

In [ ]:
df['order_time'] = pd.to_datetime(df['order_time'], format='%H:%M:%S')
print(df['order_time'].dtype)

df['order_time'] = df['order_time'].dt.strftime('%H:%M:%S')

print(df['order_time'].head(5))
print(df['order_time'].dtype)

datetime64[ns]
0    11:38:36
1    11:57:40
2    11:57:40
3    11:57:40
4    11:57:40
Name: order_time, dtype: object
object

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed', dayfirst=False)
print(df['order_date'].dtype)

datetime64[ns]

In [ ]:
df['month'] = df['order_date'].dt.month

print(df['month'].head(5))

0    1
1    1
2    1
3    1
4    1
Name: month, dtype: int32

In [ ]:
df['month_name'] = df['order_date'].dt.month_name()
print(df['month_name'].head(5))

0    January
1    January
2    January
3    January
4    January
Name: month_name, dtype: object

In [ ]:
df['day_of_week'] = df['order_date'].dt.day_name()
print(df['day_of_week'].head(5))

0    Thursday
1    Thursday
2    Thursday
3    Thursday
4    Thursday
Name: day_of_week, dtype: object

In [ ]:
df['quarter'] = df['order_date'].dt.quarter
print(df['quarter'].head(5))

0    1
1    1
2    1
3    1
4    1
Name: quarter, dtype: int32

In [ ]:
df['order_time'] = pd.to_datetime(df['order_time'], format='%H:%M:%S')
df['hour'] = df['order_time'].dt.hour

print(df['hour'].head(5))

0    11
1    11
2    11
3    11
4    11
Name: hour, dtype: int32

In [ ]:
print(df[['order_date', 'month', 'month_name', 'day_of_week', 'quarter', 'hour']].head(5))

  order_date  month month_name day_of_week  quarter  hour
0 2015-01-01      1    January    Thursday        1    11
1 2015-01-01      1    January    Thursday        1    11
2 2015-01-01      1    January    Thursday        1    11
3 2015-01-01      1    January    Thursday        1    11
4 2015-01-01      1    January    Thursday        1    11

In [ ]:
print(df.columns.tolist())

['pizza_id', 'order_id', 'pizza_name_id', 'quantity', 'order_date', 'order_time', 'unit_price', 'total_price', 'pizza_size', 'pizza_category', 'pizza_ingredients', 'pizza_name', 'month', 'month_name', 'day_of_week', 'quarter', 'Hour', 'hour']

In [ ]:
df = df.drop(columns=['pizza_name_id'])

In [ ]:
print(df.columns.tolist())

['pizza_id', 'order_id', 'quantity', 'order_date', 'order_time', 'unit_price', 'total_price', 'pizza_size', 'pizza_category', 'pizza_ingredients', 'pizza_name', 'month', 'month_name', 'day_of_week', 'quarter', 'Hour', 'hour']

In [ ]:
print("Shape  :", df.shape)
print("Nulls  :", df.isnull().sum().sum())
print("Columns:", df.columns.tolist())
df.head()

Shape  : (24536, 17)
Nulls  : 0
Columns: ['pizza_id', 'order_id', 'quantity', 'order_date', 'order_time', 'unit_price', 'total_price', 'pizza_size', 'pizza_category', 'pizza_ingredients', 'pizza_name', 'month', 'month_name', 'day_of_week', 'quarter', 'Hour', 'hour']

,pizza_id,order_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name,month,month_name,day_of_week,quarter,Hour,hour
0,1,1,1,2015-01-01,1900-01-01 11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza,1,January,Thursday,1,11,11
1,2,2,1,2015-01-01,1900-01-01 11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza,1,January,Thursday,1,11,11
2,3,2,1,2015-01-01,1900-01-01 11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza,1,January,Thursday,1,11,11
3,4,2,1,2015-01-01,1900-01-01 11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza,1,January,Thursday,1,11,11
4,5,2,1,2015-01-01,1900-01-01 11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza,1,January,Thursday,1,11,11

In [ ]:
df['order_time'] = pd.to_datetime(df['order_time'], format='%H:%M:%S')

df['hour'] = df['order_time'].dt.hour

df['order_time'] = df['order_time'].dt.strftime('%H:%M:%S')

print(df[['order_time', 'hour']].head(5))
print(df['order_time'].dtype)

  order_time  hour
0   11:38:36    11
1   11:57:40    11
2   11:57:40    11
3   11:57:40    11
4   11:57:40    11
object

In [ ]:
df.head()

,pizza_id,order_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name,month,month_name,day_of_week,quarter,Hour,hour
0,1,1,1,2015-01-01,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza,1,January,Thursday,1,11,11
1,2,2,1,2015-01-01,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza,1,January,Thursday,1,11,11
2,3,2,1,2015-01-01,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza,1,January,Thursday,1,11,11
3,4,2,1,2015-01-01,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza,1,January,Thursday,1,11,11
4,5,2,1,2015-01-01,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza,1,January,Thursday,1,11,11

In [ ]:
df.to_csv('pizza_sales_cleaned.csv', index=False)
print("File saved successfully!")

File saved successfully!

In [ ]:
df = df.drop(columns=['pizza_ingredients'])

In [ ]:
df.to_csv('pizza_sales_cleaned.csv', index=False)
print("File saved successfully!")

File saved successfully!

In [ ]:
df['calculated_price'] = df['unit_price'] * df['quantity']

mismatch = df[df['calculated_price'] != df['total_price']]
print("Mismatches:", len(mismatch))
print(mismatch[['pizza_name', 'quantity', 'unit_price', 'total_price', 'calculated_price']].head(10))

Mismatches: 0
Empty DataFrame
Columns: [pizza_name, quantity, unit_price, total_price, calculated_price]
Index: []

In [ ]:
df.head()

,pizza_id,order_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_name,month,month_name,day_of_week,quarter,Hour,hour,calculated_price
0,1,1,1,2015-01-01,11:38:36,13.25,13.25,M,Classic,The Hawaiian Pizza,1,January,Thursday,1,11,11,13.25
1,2,2,1,2015-01-01,11:57:40,16.00,16.00,M,Classic,The Classic Deluxe Pizza,1,January,Thursday,1,11,11,16.00
2,3,2,1,2015-01-01,11:57:40,18.50,18.50,L,Veggie,The Five Cheese Pizza,1,January,Thursday,1,11,11,18.50
3,4,2,1,2015-01-01,11:57:40,20.75,20.75,L,Supreme,The Italian Supreme Pizza,1,January,Thursday,1,11,11,20.75
4,5,2,1,2015-01-01,11:57:40,16.00,16.00,M,Veggie,The Mexicana Pizza,1,January,Thursday,1,11,11,16.00

In [ ]:
df = df.drop(columns=['total_price'])

In [ ]:
df = df.rename(columns={'calculated_price': 'total_price'})
print(df.columns.tolist())

['pizza_id', 'order_id', 'quantity', 'order_date', 'order_time', 'unit_price', 'pizza_size', 'pizza_category', 'pizza_name', 'month', 'month_name', 'day_of_week', 'quarter', 'Hour', 'hour', 'total_price']

In [ ]:
df.head()

,pizza_id,order_id,quantity,order_date,order_time,unit_price,pizza_size,pizza_category,pizza_name,month,month_name,day_of_week,quarter,Hour,hour,total_price
0,1,1,1,2015-01-01,11:38:36,13.25,M,Classic,The Hawaiian Pizza,1,January,Thursday,1,11,11,13.25
1,2,2,1,2015-01-01,11:57:40,16.00,M,Classic,The Classic Deluxe Pizza,1,January,Thursday,1,11,11,16.00
2,3,2,1,2015-01-01,11:57:40,18.50,L,Veggie,The Five Cheese Pizza,1,January,Thursday,1,11,11,18.50
3,4,2,1,2015-01-01,11:57:40,20.75,L,Supreme,The Italian Supreme Pizza,1,January,Thursday,1,11,11,20.75
4,5,2,1,2015-01-01,11:57:40,16.00,M,Veggie,The Mexicana Pizza,1,January,Thursday,1,11,11,16.00

In [ ]:
df.to_csv('pizza_sales_cleaned2.csv', index=False)
print("Saved ✅")

Saved ✅

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df_raw = pd.read_csv('pizza_sales.csv')

# Check rows where quantity > 1
print(df_raw[df_raw['quantity'] > 1][['pizza_name', 'quantity', 'unit_price', 'total_price']].head(10))

                       pizza_name  quantity  unit_price  total_price
48        The Mediterranean Pizza       2.0       16.00        32.00
183       The Spicy Italian Pizza       3.0       20.75        62.25
211    The Barbecue Chicken Pizza       2.0       20.75        41.50
222               The Greek Pizza       2.0       16.00        32.00
245            The Hawaiian Pizza       2.0       10.50        21.00
341    The Barbecue Chicken Pizza       3.0       16.75        50.25
444            The Big Meat Pizza       2.0       12.00        24.00
456     The Chicken Alfredo Pizza       2.0       20.75        41.50
611  The California Chicken Pizza       2.0       16.75        33.50
612     The Chicken Alfredo Pizza       2.0       16.75        33.50

In [ ]:
print("Total Revenue:", round(df['total_price'].sum(), 2))

Total Revenue: 413222.4

In [ ]:
df['total_price'] = df['unit_price'] * df['quantity']
print("After fix:", round(df['total_price'].sum(), 2))

After fix: 413222.4

In [ ]:
df = pd.read_csv('pizza_sales.csv')
print("Total Revenue:", round(df['total_price'].sum(), 2))

df['total_price'].sum()

Total Revenue: 817860.05

np.float64(817860.05)

In [ ]:
df.to_csv('pizza_sales_cleaned.csv', index=False)
print("Saved ✅")

Saved ✅

In [ ]:
df.to_csv('pizza_sales_cleaned.csv', index=False)
print("Saved ✅")

Saved ✅